AllCops:
  SuggestExtensions: false
  NewCops: enable
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/Documentation:
  Enabled: false
Style/Alias:
  Enabled: false
Style/Lambda:
  Enabled: false
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2
Style/FormatStringToken:
  Enabled: false
Layout/TrailingEmptyLines:
  EnforcedStyle: final_blank_line
Layout/TrailingWhitespace:
  Enabled: true
Layout/EmptyLines:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
Layout/EmptyLinesAroundClassBody:
  Enabled: true
Layout/EmptyLinesAroundMethodBody:
  Enabled: true
Style/NegatedIf:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
