# frozen_string_literal: true

# ======================================================
# Contains code from GitLab FOSS (MIT Licensed)
# Copyright (c) GitLab Inc.
# See .licenses/Gisia/others/gitlab-foss.dep.yml for full license
# ======================================================

module Gitlab
  module ErrorTracking
    module Processor
      module ContextPayloadProcessor
        # This processor is added to inject application context into Sentry
        # events generated by Sentry built-in integrations. When the
        # integrations are re-implemented and use Gitlab::ErrorTracking, this
        # processor should be removed.
        def self.call(event)
          Gitlab::ErrorTracking::ContextPayloadGenerator.generate(nil, {}).each do |key, value|
            event.public_send(key).deep_merge!(value) # rubocop:disable GitlabSecurity/PublicSend
          end

          event
        end
      end
    end
  end
end
