get 'users', to: 'users#index'
post 'users', to: 'users#create'
get 'users/:id', to: 'users#find_user'
put 'users/:id', to: 'users#update'
delete 'users/:id', to: 'users#destroy'
get 'user', to: 'users#show'
